### ISSUE TITLE
I can not install microscope v2 successfully

### ISSUE THREAD

**Issue by NoelCarlton** [cryptape/microscope-v2#108]
here are the outputs. I've tried on several new Centos7 systems and got the same issue, so I put the trouble here:
```
[5/5] Building fresh packages...
[-/10] ⠐ waiting...
[-/10] ⠐ waiting...
[7/10] ⠐ scrypt
[6/10] ⠐ websocket
error /home/noel/microscope-v2/node_modules/sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /home/noel/microscope-v2/node_modules/sha3
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.16.0 | linux | x64
gyp info find Python using Python version 2.7.5 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v14.16.0/node-v14.16.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v14.16.0/node-v14.16.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v14.16.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v14.16.0/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/src/node-v14/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/noel/microscope-v2/node_modules/sha3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/src/node-v14/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/noel/.cache/node-gyp/14.16.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/noel/.cache/node-gyp/14.16.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/src/node-v14/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/noel/.cache/node-gyp/14.16.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/noel/microscope-v2/node_modules/sha3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/usr/local/src/node-v14/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/src/node-v14/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/usr/local/src/node-v14/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/usr/local/src/node-v14/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    options.duplicate_basename_check)
  File "/usr/local/src/node-v14/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 139, in Load
    params['parallel'], params['root_targets'])
  File "/usr/local/src/node-v14/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2783, in Load
    variables, includes, depth, check, True)
  File "/usr/local/src/node-v14/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 392, in LoadTargetBuildFile
    includes, True, check)
  File "/usr/local/src/node-v14/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 264, in LoadOneBuildFile
    aux_data, includes, check)
  File "/usr/local/src/node-v14/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 301, in LoadBuildFileIncludesIntoDict
    LoadOneBuildFile(include, data, aux_data, None, False, check),
  File "/usr/local/src/node-v14/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 244, in LoadOneBuildFile
    None)
  File "/home/noel/.cache/node-gyp/14.16.0/include/node/common.gypi", line 151
    'Optimi
          ^
SyntaxError: EOL while scanning string literal
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/src/node-v14/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 3.10.0-862.el7.x86_64
gyp ERR! command "/usr/local/src/node-v14/bin/node" "/usr/local/src/node-v14/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/noel/microscope-v2/node_modules/sha3
```
![image](https://user-images.githubusercontent.com/15320741/109406207-3b3e2480-79b2-11eb-81fc-6d9ba84f14ec.png)

**Comment by zhendexuebuhui** [comment]
error /home/noel/microscope-v2/node_modules/sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild

please install and use node ^10.13.0 32-bit 
then 
npm install -g node-gyp

**Comment by dont-see-big-shark** [comment]
Please use node v10 instead

**Comment by NyanShen** [comment]
use node v10 is not ok so many errors

**Comment by NyanShen** [comment]
Unhandled rejection Error: Command failed: /usr/local/bin/git clone --depth=1 -q -b browserifyCompatible git://github.com/frozeman/WebSocket-Node.git /Users/nyan/.npm/_cacache/tmp/git-clone-4d1b6602
/Users/nyan/.npm/_cacache/tmp/git-clone-4d1b6602/.git: Permission denied

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)

**Comment by NyanShen** [comment]
npm WARN Microscope@2.0.0 No repository field.
npm WARN Microscope@2.0.0 No license field.

npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git
npm ERR! 
npm ERR! undefined
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nyan/.npm/_logs/2023-01-06T01_40_41_179Z-debug.log

**Comment by alexbrave** [comment]
I'm wondering if this is an apple silicon issue. I'm also getting a similar error for an old codebase that I'm trying to run on an M2 mac.
Edit: sorry I see now you mentioned CentOS

**Comment by christhomas** [comment]
I'm having this problem on a windows machine
